server:
  port: 8070

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: students

    config:
      student-url: http://localhost:8090
      import: optional:configserver:http://localhost:8889

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL_SCHOOLS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka