server:
  port: 8090

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: schools

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL_SCHOOLS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect