services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: students
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data.dialect.PostgreSQLDialect