server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    driven-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: username
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect